import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Flex, Select } from "antd";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  // variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  // variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // function onChange () {
  // }
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${geistMono.className}`}>
        {/* <Flex gap="middle" align="end" vertical>
          <Select
            defaultValue="lucy"
            style={{
              width: 120,
            }}
            // onChange={handleChange}
            options={[
              {
                value: 'jack',
                label: 'Jack',
              },
              {
                value: 'lucy',
                label: 'Lucy',
              },
            ]}
          />
        </Flex> */}
        {children}
      </body>
    </html >
  );
}
