// "use client";
// 'use strict'
// import './i18n';
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // function onChange () {
  // }
  return (
    <html lang="en">
      {/* ${geistMono.className} */}
      <body className={`${geistSans.className}`}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html >
  );
}
